# PexoraProxy Konfiguration
# Diese Datei enthält zentrale Einstellungen für das Proxy-System

# Aktiviert detaillierte Debug-Ausgabe in der Konsole
debug-mode: false

# Module automatisch neu laden, wenn der Core neu geladen wird
module-auto-reload: true

# Proxy-Messaging-Kanal-Einstellungen
messaging:
  # Channel-Name für die Kommunikation zwischen Proxy und Servern
  channel-name: "pexora:core"
  
  # Aktiviere/Deaktiviere die Verschlüsselung der Nachrichten
  encryption-enabled: false
  
  # Verschlüsselungsschlüssel (falls aktiviert)
  encryption-key: "ChangeThisToASecureKey!"

# Datenbankeinstellungen (wird für Module und Synchronisation verwendet)
database:
  enabled: true
  type: "mysql"    # Aktuell unterstützt: mysql
  host: "localhost"
  port: 3306
  name: "pexora"
  user: "root"
  password: ""
  
  # Verbindungspool-Einstellungen
  pool:
    min-size: 5
    max-size: 10
    idle-timeout: 300000  # 5 Minuten
    max-lifetime: 1800000 # 30 Minuten
  
  # Automatische Tabellenerstellung bei erstem Start
  auto-create-tables: true

# Modul-Einstellungen
modules:
  # Aktiviert die Erkennung von Nicht-Pexora-Modulen (ohne "Pexora"-Präfix)
  allow-non-pexora-modules: true
  
  # Liste von Plugin-Namen, die als Module geladen werden sollen, auch wenn sie nicht mit "Pexora" beginnen
  additional-modules:
    - "MeinProxyPlugin1"
    - "MeinProxyPlugin2"
    
  # Ignoriere die Namenskonvention (Pexora-Präfix) für alle Module
  ignore-naming-convention: false

  # Automatisches Kopieren von Plugins in das Modul-Verzeichnis aktivieren
  # Wenn aktiviert, werden Plugins, die PexoraProxy als Abhängigkeit haben,
  # automatisch aus dem plugins-Verzeichnis in das modules-Verzeichnis kopiert
  auto-copy-to-modules: false
  
  # Lösche alte Plugins im plugins-Verzeichnis, nachdem sie kopiert wurden
  # Diese Einstellung ist nur wirksam, wenn auto-copy-to-modules aktiviert ist
  delete-old-plugins: false